src/objects/Level__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Current_Question__c</fullName>
        <label>Current Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_Play__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Play</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Chatter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Update Chatter</label>
        <type>Checkbox</type>
    </fields>
    <label>Level</label>
</CustomObject>

src/objects/Question_Post__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Answered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Answered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Post_Id__c</fullName>
        <label>Post Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Id__c</fullName>
        <label>Question Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Post</label>
</CustomObject>

src/classes/FeedItemTriggerHandler.cls
public class FeedItemTriggerHandler {

	private static Boolean hasRun = false;

	public static void checkForAnswers(List<FeedComment> feedcomments){

		// This doesn't deal with multiple batches
		// But we really shouldn't process more than one comment at a time
		if(hasRun)
			return;

		hasRun = true;

		List<ChatterEvent> responses = new List<ChatterEvent>();

		List<Level__c> levels = [SELECT Name, Class_Name__c, Current_Question__c FROM Level__c WHERE In_Play__c = true];
		if(levels.isEmpty())
			return;

		LevelWrapper level = new LevelWrapper(levels[0]);

		if(level.getCurrentQuestionSettings().Answered__c)
			return;

		Question_Post__c qp = level.getCurrentQuestionSettings();

		for(FeedComment comment : feedComments){

			if(comment.CreatedById != UserInfo.getUserId())
				continue;

			if(qp.Post_Id__c != comment.FeedItemId || qp.Answered__c)
				continue;

			responses.add(level.getCurrentQuestion().readPlayersChatterComment(comment, qp.Question_Id__c));

		}

		List<FeedComment> comments = new List<FeedComment>();
		List<FeedItem> items = new List<FeedItem>();

		for(ChatterEvent ce : responses){
			if(ce == null)
				continue;

			if(ce.PostComment != null){
				ce.PostComment.CreatedById = Beacon.readSetting('TheGuideId');
				comments.add(ce.PostComment);
			}

			if(ce.PostDetails != null){
				ce.PostDetails.CreatedById = Beacon.readSetting('TheGuideId');
				items.add(ce.PostDetails);
			}
		}

		insert comments;
		insert items;

		if(!comments.isEmpty() || !items.isEmpty()){
			level.levelSettings.Update_Chatter__c = true;
			update level.levelSettings;
		}

	}

}